# Generated by Django 5.1.1 on 2024-10-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseballStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=255)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveIntegerField(default=2024)),
                ('bats', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Both')], default='L', max_length=1)),
                ('age', models.PositiveIntegerField(default=0, max_length=2, verbose_name='Age That Year')),
                ('hits', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
