# Generated by Django 5.1.1 on 2024-10-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseballstats',
            options={'ordering': ('rank',)},
        ),
        migrations.AlterField(
            model_name='baseballstats',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='Age That Year'),
        ),
    ]
