# Generated by Django 5.1.1 on 2024-10-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_alter_baseballstats_options_alter_baseballstats_age'),
    ]

    operations = [
    ]
