# Generated by Django 5.1.1 on 2024-10-02 20:23

from django.db import migrations
import requests


def import_stats(apps, _):
    BaseballStats = apps.get_model("baseball", "BaseballStats")
    api_url = "https://api.sampleapis.com/baseball/hitsSingleSeason"
    response = requests.get(api_url)
    api_stats = response.json()
    stats = []

    for indx, stat in enumerate(api_stats, start=1):
        stats.append(BaseballStats(player=stat["Player"],
                                   rank=indx,
                                   year=stat["Year"],
                                   bats=stat["Bats"],
                                   age=stat["AgeThatYear"],
                                   hits=stat["Hits"]))

    BaseballStats.objects.bulk_create(stats)


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_alter_baseballstats_options_alter_baseballstats_age'),
    ]

    operations = [
        migrations.RunPython(code=import_stats, reverse_code=migrations.RunPython.noop)
    ]
