# Generated by Django 5.1.1 on 2024-10-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0003_auto_20241002_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseballstats',
            options={'ordering': ('rank',), 'verbose_name_plural': 'Baseball Stats'},
        ),
    ]
